### ISSUE TITLE
Make plugin work with Google Cloud Storage

### ISSUE THREAD

**Issue by openforest** [tc-mccarthy/tcs3#24]
Hi TC,
Not an issue but a feature request:
It would be great to patch tcs3 (https://wordpress.org/plugins/tcs3/) to work with Google Cloud Storage (which supports the S3 API). 
https://tim.purewhite.id.au/2015/10/wordpress-google-cloud-storage/ describes the functionality I want, but uses WP Offload S3 (https://wordpress.org/plugins/amazon-s3-and-cloudfront/), which, in the free version has limited abilities. 
It would be great to add an option in the interface to ask whether the Admin wants it to work for Amazon S3 or GCS; then let the Admin enter/save the required URL/credentials.

**Comment by tc-mccarthy** [comment]
@openforest I will definitely look in to this -- I haven't much experience with GCS nor a use-case that would provide a suitable sandbox environment for this so it may take me some time.

**Comment by openforest** [comment]
Hi TC,
I have asked a coder to make the changes. Attached is the modified plugin. I am not a coder, so this Github checking in/out is a distant foreign language to me. It would be great if you could test and if you like it merge the code with your plugin.
[tcs3-gcs.zip](https://github.com/tc-mccarthy/tcs3/files/159883/tcs3-gcs.zip)

**Comment by openforest** [comment]
Hi TC,
Could you look into this? Here is an updated version, with a small bug fix in the original code: a hard link to the tcs3 directory replaced with a soft link (as we tested in a separate directory; and then the code did not work).
[tcs3-gcs_v3.zip](https://github.com/tc-mccarthy/tcs3/files/236541/tcs3-gcs_v3.zip)

**Comment by tc-mccarthy** [comment]
Closed this because this plugin is very much geared toward S3 right now. A release of version 2.0 is coming in just weeks and this won't be in there. Perhaps I can revisit in the future.
