### ISSUE TITLE
TcS3 work with Iam Roles (Instance Profiles)1

### ISSUE THREAD

**Issue by Murteas** [tc-mccarthy/tcs3#25]
More of a feature request/question.   The setup I have for the wordpress instance I am managing, doesn't permit me to see the credentials (access key and secret key) of the Iam User I am using to access s3.  I do however have the Iam role that is used, and it grants me the rights I need to access those resources.   Is there anyway to just pass in the role being used, and use instance profiles with TCS3?

**Comment by tc-mccarthy** [comment]
Murteas I will look into this!

**Comment by Murteas** [comment]
Actually, I've been playing around with your code, and I was able to get it working just by leaving the access and secret keys completely blank (and making them not required).   The AWS credentials code you have in their already picks up the case where you are in AWS and trying to access an s3 bucket with the correct IAM role.  It is actually pretty awesome!  
In tcs3.php I just had to modify 1 line: 
 `//MODIFIED 04/27/2016 - Don't require the access & secret key - we are using IAm roles
		$use_S3 = ($this->options["bucket"] != "" && $this->options["bucket_path"] != "" && $this->options["bucket_region"] != "") ? true : false;
		//$use_S3 = ($this->accessKey != "" && $this->accessSecret != "" && $this->options["bucket"] != "" && $this->options["bucket_path"] != "" && $this->options["bucket_region"] != "") ? true : false;
`
