### ISSUE TITLE
Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by 1gor** [tc-mccarthy/tcs3#33]
When activating the plugin using official wordpress docker image (docker is in swarm configuration) I got the following error:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function plugin_dir_url(), 0 passed in /var/www/html/wp-content/plugins/tcs3/classes/tcS3.class.php on line 22 and exactly 1 expected in /var/www/html/wp-includes/plugin.php:732 Stack trace: #0 /var/www/html/wp-content/plugins/tcs3/classes/tcS3.class.php(22): plugin_dir_url() #1 /var/www/html/wp-content/plugins/tcs3/tcS3.php(21): tcS3->__construct() #2 /var/www/html/wp-settings.php(305): include_once('/var/www/html/w...') #3 /var/www/html/wp-config.php(95): require_once('/var/www/html/w...') #4 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #5 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...') #6 /var/www/html/index.php(17): require('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-includes/plugin.php on line 732`

It seems that error control operator  `@` on line 22 ( `@plugin_dir_url();`) somehow becomes disabled in this particular docker configuration. Which results in a fatal error because of the missing argument. 

While I should obviously investigate the environment that triggers this error, may I ask what was the point of putting here this function without required argument and ignoring the resulting errors? Why not simply use 

```        $this->pluginDir = plugin_dir_url(__FILE__).'../../';    ```

on line 22 ?

**Comment by tc-mccarthy** [comment]
Version 2.0 imminent. Resolved this issue
