### ISSUE TITLE
Suggestion: Make the plugin Multisite compatible

### ISSUE THREAD

**Issue by Lunteer** [tc-mccarthy/tcs3#36]
First off, great plugin! Thanks for all the hard work.

Suggestion. Make the plugin Multisite compatible. I added it to the mu-plugins folder and could not the setting page anywhere.

Here are s few suggestions:
1) On the super admin section add a TCS3 settings page with all the current settings
2) We are running multiple client sites and we do not want each client to have assets loading from our subdomain assests.ourcompany.com but from their subdomain assets.clientsdomain.com. so not 100% sure what this entails but, 
2a) on each site allow the admin to select what will be the subdomain for their images, etc. WP knows their site ID so it can rewrite the URLs.
2b) The user will need to setup a CNAME or A record for that subdomain
2c) Bonus, Run a check to see if user subdomain is working, if so rewrite URLs, if not, keep it as the setup from the superadmin settings.

Just to be clear we do not want each client to have to setup their own s3 bucket and cloudfront, etc. We wan them to use our setup but just change the subdomain to match their domain (for branding purposes)

Happy to help if I can

**Comment by tc-mccarthy** [comment]
Thanks for the request! This functionality already exists -- if you add the plugin to wp-content/plugins and network activate it every site will be automatically set up. Once you've done this, the network settings page will have a tcS3 admin pane where you can build out the configuration. Each site will also get the tcS3 admin pane as well -- but you only need to fill in the values you want to override for that particular site. Any other values will be inherited from the network configuration.

**Comment by Lunteer** [comment]
Thanks for pointing that out. I always forget that it can be network activated :)
When I did network activate I sometimes get the below error. Did not setup anything just network activated

`Fatal error: Uncaught Error: Call to undefined function is_plugin_active_for_network() in /var/www/wp-content/plugins/tcs3/inc/base.class.php:19 Stack trace: #0 /var/www/wp-content/plugins/tcs3/inc/base.class.php(12): tcs3_base->network_activation_check() #1 /var/www/wp-content/plugins/tcs3/tcS3.php(25): tcs3_base->__construct() #2 /var/www/wp-includes/class-wp-hook.php(286): tcs3->init('') #3 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /var/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /var/www/wp-settings.php(434): do_action('after_setup_the...') #6 /var/www/wp-config.php(103): require_once('/var/www/wp-set...') #7 /var/www/wp-load.php(37): require_once('/var/www/wp-con...') #8 /var/www/wp-admin/admin.php(31): require_once('/var/www/wp-loa...') #9 /var/www/wp-admin/index.php(10): require_once('/var/www/wp-adm...') #10 {main} thrown in /var/www/wp-content/plugins/tcs3/inc/base.class.php on line 19`

**Comment by Lunteer** [comment]
I tried activating on just one site and the site went down with 500 error.

Here is the error log from Nginx.
`#2 /var/www/wp-includes/class-wp-hook.php(286): tcs3->init('')
#3 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /var/www/wp-settings.php(434): do_action('after_setup_the...')
#6 /var/www/wp-config.php(103): require_once('/var/www/wp-set...')
#7 /var/www/wp-load.php(37): require_once('/var/www/wp-con...')
#8 /var/www/wp-admin/admin.php(31): require_once('/var/www/wp-loa...')
#9 /var/www/wp-admin/index.php(10): require_once('/var/www/wp-adm...')
#10 {main}
  thrown in /var/www/wp-content/plugins/tcs3/inc/base.class.php on line 19" while reading response header from upstream, client: 77.139.128.190, server:...`

Seems they are both related
