### ISSUE TITLE
Issue when activating site-wide or individual site

### ISSUE THREAD

**Issue by Lunteer** [tc-mccarthy/tcs3#37]
Hey. I get this error when activating the plugin on a WP Network installation. This happens both when activating on a sitewide setting (from superAdmin) and when activating on individual sites.

Fatal error: Uncaught Error: Call to undefined function is_plugin_active_for_network() in /var/www/wp-content/plugins/tcs3/inc/base.class.php:19 Stack trace: #0 /var/www/wp-content/plugins/tcs3/inc/base.class.php(12): tcs3_base->network_activation_check() #1 /var/www/wp-content/plugins/tcs3/tcS3.php(25): tcs3_base->__construct() #2 /var/www/wp-includes/class-wp-hook.php(286): tcs3->init('') #3 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /var/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /var/www/wp-settings.php(434): do_action('after_setup_the...') #6 /var/www/wp-config.php(103): require_once('/var/www/wp-set...') #7 /var/www/wp-load.php(37): require_once('/var/www/wp-con...') #8 /var/www/wp-admin/admin.php(31): require_once('/var/www/wp-loa...') #9 /var/www/wp-admin/index.php(10): require_once('/var/www/wp-adm...') #10 {main} thrown in /var/www/wp-content/plugins/tcs3/inc/base.class.php on line 19

Thanks!

**Comment by tc-mccarthy** [comment]
This is fixed in the latest version. Thanks for reporting!
