### ISSUE TITLE
Errors when trying to Sync

### ISSUE THREAD

**Issue by Lunteer** [tc-mccarthy/tcs3#39]
Hey.

A few issues and suggestions:

1) When in the admin SuperAdmin, the update and sync button does not work (but get no errors in logs). This might be a bug but if not the network admin would probably want a way to update the entire network (we would 😄 ). 

Side note: We are on EC2 so we used `cp --recursive /path/to/folder {example: var/www/wp-content/uploads/} s3://bucket-name/folder/` to push on content onto the S3 bucket

2) We get the following errors when trying to sync on individual sites
`12924#0: *161140 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method tcs3_ajax::get_path_from_file() in /var/www/wp-content/plugins/tcs3/inc/wp_ajax.class.php:39
Stack trace:
#0 /var/www/wp-includes/class-wp-hook.php(286): tcs3_ajax->sync_all('')
#1 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/wp-admin/admin-ajax.php(97): do_action('wp_ajax_sync_al...')
#4 {main}
  thrown in /var/www/wp-content/plugins/tcs3/inc/wp_ajax.class.php on line 39" while reading response header from upstream, client: , server: , request: "POST /site/wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "", referrer: ".com/sites/wp-admin/admin.php?page=tcs3-admin&tab=sync"
`

**Comment by tc-mccarthy** [comment]
@Lunteer, 

Weird. I will try and find time to take a look at this but if you use the aws cli you can just do `aws s3 sync /path/to/uploads s3://BUCKET_NAME/BUCKET_PATH`

**Comment by Lunteer** [comment]
Thanks for the help I knew about cp but not sync. Thanks
